#!/bin/bash
# OPUS 67 Launcher - Shows status then starts Claude Code
# Auto-generated by opus67 init

# ANSI color codes
CYAN='\033[36m'
YELLOW='\033[1;33m'
GREEN='\033[32m'
GRAY='\033[90m'
RESET='\033[0m'

# Print OPUS 67 banner
echo ""
echo -e "${CYAN}╔═══════════════════════════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}║  ${YELLOW}OPUS 67 v6.0.0${CYAN} │ ${GREEN}● ONLINE${CYAN} │ Skills: 141 │ MCPs: 82     ║${RESET}"
echo -e "${CYAN}╚═══════════════════════════════════════════════════════════════╝${RESET}"

# Detect project type and show relevant skills
detect_project() {
    if [ -f "Anchor.toml" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}solana${GRAY} │ Skills: solana-anchor-expert, rust-patterns${RESET}"
    elif [ -f "next.config.ts" ] || [ -f "next.config.js" ] || [ -f "next.config.mjs" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}nextjs${GRAY} │ Skills: nextjs-14-expert, app-router${RESET}"
    elif [ -f "vite.config.ts" ] || [ -f "vite.config.js" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}vite${GRAY} │ Skills: react-typescript, vite-config${RESET}"
    elif [ -f "Cargo.toml" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}rust${GRAY} │ Skills: rust-advanced, memory-safety${RESET}"
    elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}python${GRAY} │ Skills: python-best-practices, fastapi${RESET}"
    elif [ -f "go.mod" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}go${GRAY} │ Skills: go-patterns, go-concurrency${RESET}"
    elif [ -f "package.json" ]; then
        echo -e "${GRAY}├─ Project: ${CYAN}node${GRAY} │ Skills: nodejs-backend, typescript${RESET}"
    else
        echo -e "${GRAY}├─ Project: ${CYAN}generic${GRAY} │ Skills: base${RESET}"
    fi
}

detect_project
echo ""

# Find and run the real Claude Code binary
# Check common locations
if command -v claude.cmd &> /dev/null; then
    # Windows with .cmd extension available
    claude.cmd "$@"
elif [ -f "/c/Users/$USER/AppData/Roaming/npm/claude.cmd" ]; then
    # Windows Git Bash - npm global
    "/c/Users/$USER/AppData/Roaming/npm/claude.cmd" "$@"
elif [ -f "$HOME/AppData/Roaming/npm/claude.cmd" ]; then
    # Windows - alternate path format
    "$HOME/AppData/Roaming/npm/claude.cmd" "$@"
elif [ -f "/usr/local/bin/claude" ]; then
    # macOS/Linux - Homebrew or system install
    /usr/local/bin/claude "$@"
elif [ -f "$HOME/.local/bin/claude" ]; then
    # Linux - user local install
    "$HOME/.local/bin/claude" "$@"
elif command -v npx &> /dev/null; then
    # Fallback to npx
    npx @anthropic/claude-code "$@"
else
    echo "Error: Could not find Claude Code installation"
    echo "Please ensure Claude Code is installed: npm install -g @anthropic/claude-code"
    exit 1
fi
