/**
 * Shell Alias Setup for OPUS 67
 * Creates wrapper script and adds alias to user's shell profile
 */

import {
  readFileSync,
  writeFileSync,
  existsSync,
  mkdirSync,
  chmodSync,
} from "fs";
import { join, dirname } from "path";
import { homedir, platform } from "os";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Launcher script content
const LAUNCHER_SCRIPT = `#!/bin/bash
# OPUS 67 Launcher - Shows status then starts Claude Code
# Auto-generated by opus67 init

# ANSI color codes
CYAN='\\033[36m'
YELLOW='\\033[1;33m'
GREEN='\\033[32m'
GRAY='\\033[90m'
RESET='\\033[0m'

# Print OPUS 67 banner
echo ""
echo -e "\${CYAN}╔═══════════════════════════════════════════════════════════════╗\${RESET}"
echo -e "\${CYAN}║  \${YELLOW}OPUS 67 v6.0.0\${CYAN} │ \${GREEN}● ONLINE\${CYAN} │ Skills: 141 │ MCPs: 82     ║\${RESET}"
echo -e "\${CYAN}╚═══════════════════════════════════════════════════════════════╝\${RESET}"

# Detect project type and show relevant skills
detect_project() {
    if [ -f "Anchor.toml" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}solana\${GRAY} │ Skills: solana-anchor-expert, rust-patterns\${RESET}"
    elif [ -f "next.config.ts" ] || [ -f "next.config.js" ] || [ -f "next.config.mjs" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}nextjs\${GRAY} │ Skills: nextjs-14-expert, app-router\${RESET}"
    elif [ -f "vite.config.ts" ] || [ -f "vite.config.js" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}vite\${GRAY} │ Skills: react-typescript, vite-config\${RESET}"
    elif [ -f "Cargo.toml" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}rust\${GRAY} │ Skills: rust-advanced, memory-safety\${RESET}"
    elif [ -f "requirements.txt" ] || [ -f "pyproject.toml" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}python\${GRAY} │ Skills: python-best-practices, fastapi\${RESET}"
    elif [ -f "go.mod" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}go\${GRAY} │ Skills: go-patterns, go-concurrency\${RESET}"
    elif [ -f "package.json" ]; then
        echo -e "\${GRAY}├─ Project: \${CYAN}node\${GRAY} │ Skills: nodejs-backend, typescript\${RESET}"
    else
        echo -e "\${GRAY}├─ Project: \${CYAN}generic\${GRAY} │ Skills: base\${RESET}"
    fi
}

detect_project
echo ""

# Find and run the real Claude Code binary
if command -v claude.cmd &> /dev/null; then
    claude.cmd "$@"
elif [ -f "/c/Users/$USER/AppData/Roaming/npm/claude.cmd" ]; then
    "/c/Users/$USER/AppData/Roaming/npm/claude.cmd" "$@"
elif [ -f "$HOME/AppData/Roaming/npm/claude.cmd" ]; then
    "$HOME/AppData/Roaming/npm/claude.cmd" "$@"
elif [ -f "/usr/local/bin/claude" ]; then
    /usr/local/bin/claude "$@"
elif [ -f "$HOME/.local/bin/claude" ]; then
    "$HOME/.local/bin/claude" "$@"
elif command -v npx &> /dev/null; then
    npx @anthropic/claude-code "$@"
else
    echo "Error: Could not find Claude Code installation"
    echo "Please ensure Claude Code is installed: npm install -g @anthropic/claude-code"
    exit 1
fi
`;

/**
 * Detect the user's shell profile path
 */
function detectShellProfile(): string {
  const home = homedir();
  const isWindows = platform() === "win32";

  if (isWindows) {
    // Git Bash on Windows
    const bashrc = join(home, ".bashrc");
    if (existsSync(bashrc)) return bashrc;

    // Create .bashrc if it doesn't exist (Git Bash users often don't have one)
    return bashrc;
  }

  // Unix - check for zsh first (macOS default)
  const zshrc = join(home, ".zshrc");
  if (existsSync(zshrc)) return zshrc;

  // Fall back to bashrc
  const bashrc = join(home, ".bashrc");
  if (existsSync(bashrc)) return bashrc;

  // Default to bashrc
  return bashrc;
}

/**
 * Setup shell alias for OPUS 67 launcher
 */
export function setupShellAlias(): {
  success: boolean;
  launcherPath: string;
  profilePath: string;
  message: string;
} {
  const home = homedir();
  const opus67Dir = join(home, ".opus67");
  const launcherPath = join(opus67Dir, "launcher.sh");

  try {
    // 1. Create ~/.opus67 directory
    if (!existsSync(opus67Dir)) {
      mkdirSync(opus67Dir, { recursive: true });
    }

    // 2. Write launcher script
    writeFileSync(launcherPath, LAUNCHER_SCRIPT);

    // 3. Make executable (Unix and Git Bash)
    try {
      chmodSync(launcherPath, 0o755);
    } catch {
      // Ignore chmod errors on Windows
    }

    // 4. Detect and update shell profile
    const profilePath = detectShellProfile();
    const aliasLine = `alias claude='~/.opus67/launcher.sh'`;
    const aliasComment =
      "# OPUS 67 - Enhanced Claude Code with visible boot banner";

    // Read existing profile content
    let profileContent = "";
    if (existsSync(profilePath)) {
      profileContent = readFileSync(profilePath, "utf-8");
    }

    // Check if alias already exists
    if (profileContent.includes("opus67/launcher")) {
      return {
        success: true,
        launcherPath,
        profilePath,
        message: `Alias already configured in ${profilePath}`,
      };
    }

    // Add alias to profile
    const addition = `\n${aliasComment}\n${aliasLine}\n`;
    writeFileSync(profilePath, profileContent + addition);

    return {
      success: true,
      launcherPath,
      profilePath,
      message: `Shell alias added to ${profilePath}`,
    };
  } catch (error) {
    return {
      success: false,
      launcherPath,
      profilePath: "",
      message: `Failed to setup shell alias: ${error}`,
    };
  }
}

/**
 * Get instructions for activating the alias
 */
export function getActivationInstructions(profilePath: string): string {
  const isZsh = profilePath.includes(".zshrc");
  const sourceCmd = isZsh ? "source ~/.zshrc" : "source ~/.bashrc";

  return `
To activate OPUS 67 banner, either:
  1. Restart your terminal, OR
  2. Run: ${sourceCmd}

Then just type 'claude' to start Claude Code with the OPUS 67 banner!
`;
}
